[package]
name = "client"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Terah <terah.dev@gmail.com>"]

[dependencies]
common = { path = "../common" }
network = { path = "../network" }
region = { path = "../region" }
spin = "0.4.8"
log = "0.4"
nalgebra = { version= "0.15.1", features = ["serde-serialize"] }
