language: rust
sudo: required
rust:
  - nightly
addons:
    apt:
        packages:
            - libssl-dev
            - libsfml-dev
            - libcsfml-dev
            - pkg-config
            - cmake
            - zlib1g-dev
env:
  - CRATE="world"
  - CRATE="common"
  - CRATE="region"
  - CRATE="server"
  - CRATE="client"
  - CRATE="server-cli"
  - CRATE="headless"
  - CRATE="voxygen"
script:
  - cd $CRATE
  - RUST_BACKTRACE=1 cargo test -v
  - if [[ "$CRATE" == common ]] ; then RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin ; cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID ; else echo "No Code Coverage" ; fi
