[package]
name = "network"
version = "0.1.0"
authors = ["Terah <terah.dev@gmail.com>"]

[dependencies]
common = { path = "../common" }
bincode = "1.0.0"
serde = "1.0.63"
serde_derive = "1.0.63"
get_if_addrs = "0.5.2"
nalgebra = { version= "0.15.1", features = ["serde-serialize"] }
