[package]
name = "server"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Terah <terah.dev@gmail.com>"]

[dependencies]
common = { path = "../common" }
world = { path = "../world" }
network = { path = "../network" }
region = { path = "../region" }
specs = "0.11.2"
nalgebra = "0.15.1"
log = "0.4"
time = "0.1.40"
