[package]
name = "server"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Terah <terah.dev@gmail.com>"]

[dependencies]
world = { path = "../world" }
network = { path = "../network" }
specs = "0.11.2"
