[package]
name = "voxygen"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[dependencies]
client = { path = "../client" }
region = { path = "../region" }
gfx = "0.17.1"
gfx_core = "0.8.2"
gfx_window_glutin = "0.24.0"
gfx_device_gl = "0.15.0"
glutin = "0.16.0"
get_if_addrs = "0.5.2"
enum-map = "0.2.31"
nalgebra = "0.15.1"
