[package]
name = "worldtest"
version = "0.1.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]

[dependencies]
worldgen = { path = "../worldgen" }
worldsim = { path = "../worldsim" }
sfml = "0.14.0"
hsluv = "0.1.0"
